# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'degerous_object.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QLineEdit, QListWidget, QListWidgetItem,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSlider, QStackedWidget, QStatusBar,
    QTextEdit, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1200, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1200, 600))
        MainWindow.setMaximumSize(QSize(1200, 600))
        self.image_detection = QAction(MainWindow)
        self.image_detection.setObjectName(u"image_detection")
        self.video_detection = QAction(MainWindow)
        self.video_detection.setObjectName(u"video_detection")
        self.cammer_detection = QAction(MainWindow)
        self.cammer_detection.setObjectName(u"cammer_detection")
        self.yolov10_action = QAction(MainWindow)
        self.yolov10_action.setObjectName(u"yolov10_action")
        self.actionyolov10n = QAction(MainWindow)
        self.actionyolov10n.setObjectName(u"actionyolov10n")
        self.actionyolov10n_2 = QAction(MainWindow)
        self.actionyolov10n_2.setObjectName(u"actionyolov10n_2")
        self.actionyolov10s = QAction(MainWindow)
        self.actionyolov10s.setObjectName(u"actionyolov10s")
        self.actionhug = QAction(MainWindow)
        self.actionhug.setObjectName(u"actionhug")
        self.actionfaf = QAction(MainWindow)
        self.actionfaf.setObjectName(u"actionfaf")
        self.actionfaf.setCheckable(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, -21, 1200, 621))
        self.logic_page = QWidget()
        self.logic_page.setObjectName(u"logic_page")
        self.stackedWidget_2 = QStackedWidget(self.logic_page)
        self.stackedWidget_2.setObjectName(u"stackedWidget_2")
        self.stackedWidget_2.setGeometry(QRect(270, 100, 591, 381))
        self.logic_main_page = QWidget()
        self.logic_main_page.setObjectName(u"logic_main_page")
        self.checkBox_2 = QCheckBox(self.logic_main_page)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(260, 190, 82, 20))
        self.designer_putton = QPushButton(self.logic_main_page)
        self.designer_putton.setObjectName(u"designer_putton")
        self.designer_putton.setGeometry(QRect(80, 290, 431, 41))
        font = QFont()
        font.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font.setPointSize(16)
        self.designer_putton.setFont(font)
        self.lineEdit = QLineEdit(self.logic_main_page)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(80, 40, 431, 41))
        self.lineEdit_2 = QLineEdit(self.logic_main_page)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(80, 110, 431, 41))
        self.lineEdit_2.setEchoMode(QLineEdit.EchoMode.Password)
        self.checkBox = QCheckBox(self.logic_main_page)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(100, 190, 82, 20))
        self.logic_main_putton = QPushButton(self.logic_main_page)
        self.logic_main_putton.setObjectName(u"logic_main_putton")
        self.logic_main_putton.setGeometry(QRect(80, 230, 431, 41))
        self.logic_main_putton.setFont(font)
        self.renewpassword_button = QPushButton(self.logic_main_page)
        self.renewpassword_button.setObjectName(u"renewpassword_button")
        self.renewpassword_button.setGeometry(QRect(430, 190, 75, 24))
        self.renewpassword_button.setStyleSheet(u"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.stackedWidget_2.addWidget(self.logic_main_page)
        self.designer_main_page = QWidget()
        self.designer_main_page.setObjectName(u"designer_main_page")
        self.register_putton = QPushButton(self.designer_main_page)
        self.register_putton.setObjectName(u"register_putton")
        self.register_putton.setGeometry(QRect(90, 270, 161, 41))
        font1 = QFont()
        font1.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font1.setPointSize(12)
        self.register_putton.setFont(font1)
        self.register_putton.setStyleSheet(u"")
        self.lineEdit_8 = QLineEdit(self.designer_main_page)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(80, 10, 431, 41))
        self.lineEdit_9 = QLineEdit(self.designer_main_page)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(80, 60, 431, 41))
        self.lineEdit_9.setEchoMode(QLineEdit.EchoMode.Password)
        self.lineEdit_10 = QLineEdit(self.designer_main_page)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(80, 110, 431, 41))
        self.lineEdit_10.setEchoMode(QLineEdit.EchoMode.Password)
        self.lineEdit_11 = QLineEdit(self.designer_main_page)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(80, 160, 431, 41))
        self.lineEdit_12 = QLineEdit(self.designer_main_page)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(80, 210, 431, 41))
        self.exit_logic_putton = QPushButton(self.designer_main_page)
        self.exit_logic_putton.setObjectName(u"exit_logic_putton")
        self.exit_logic_putton.setGeometry(QRect(310, 270, 161, 41))
        self.exit_logic_putton.setFont(font1)
        self.exit_logic_putton.setStyleSheet(u"")
        self.stackedWidget_2.addWidget(self.designer_main_page)
        self.renewpassword_page = QWidget()
        self.renewpassword_page.setObjectName(u"renewpassword_page")
        self.lineEdit_13 = QLineEdit(self.renewpassword_page)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(90, 10, 431, 41))
        self.lineEdit_14 = QLineEdit(self.renewpassword_page)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(90, 60, 431, 41))
        self.lineEdit_14.setEchoMode(QLineEdit.EchoMode.Password)
        self.lineEdit_15 = QLineEdit(self.renewpassword_page)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(90, 110, 431, 41))
        self.lineEdit_15.setEchoMode(QLineEdit.EchoMode.Password)
        self.lineEdit_17 = QLineEdit(self.renewpassword_page)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(90, 160, 431, 41))
        self.textEdit = QTextEdit(self.renewpassword_page)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(90, 210, 431, 81))
        self.textEdit.setReadOnly(True)
        self.select_protect_password_button = QPushButton(self.renewpassword_page)
        self.select_protect_password_button.setObjectName(u"select_protect_password_button")
        self.select_protect_password_button.setGeometry(QRect(90, 310, 131, 41))
        font2 = QFont()
        font2.setPointSize(11)
        self.select_protect_password_button.setFont(font2)
        self.updata_password = QPushButton(self.renewpassword_page)
        self.updata_password.setObjectName(u"updata_password")
        self.updata_password.setGeometry(QRect(240, 310, 131, 41))
        self.updata_password.setFont(font2)
        self.exit_renew_logic_putton = QPushButton(self.renewpassword_page)
        self.exit_renew_logic_putton.setObjectName(u"exit_renew_logic_putton")
        self.exit_renew_logic_putton.setGeometry(QRect(390, 310, 131, 41))
        self.exit_renew_logic_putton.setFont(font2)
        self.stackedWidget_2.addWidget(self.renewpassword_page)
        self.stackedWidget.addWidget(self.logic_page)
        self.main_page = QWidget()
        self.main_page.setObjectName(u"main_page")
        self.listWidget = QListWidget(self.main_page)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(0, 0, 150, 600))
        self.exit_main_putton = QPushButton(self.main_page)
        self.exit_main_putton.setObjectName(u"exit_main_putton")
        self.exit_main_putton.setGeometry(QRect(0, 490, 150, 36))
        self.exit_main_putton.setFont(font1)
        self.input = QLabel(self.main_page)
        self.input.setObjectName(u"input")
        self.input.setGeometry(QRect(200, 75, 450, 450))
        self.input.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.output = QLabel(self.main_page)
        self.output.setObjectName(u"output")
        self.output.setGeometry(QRect(700, 75, 450, 450))
        self.output.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.comboBox_select_model = QComboBox(self.main_page)
        self.comboBox_select_model.setObjectName(u"comboBox_select_model")
        self.comboBox_select_model.setGeometry(QRect(0, 40, 150, 41))
        font3 = QFont()
        font3.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        self.comboBox_select_model.setFont(font3)
        self.comboBox_select_model.setStyleSheet(u"QComboBox {\n"
"    font-size: 16px; /* \u8bbe\u7f6e\u7ec4\u5408\u6846\u5185\u9009\u9879\u7684\u5b57\u4f53\u5927\u5c0f */\n"
"    text-align: center; /* \u8bbe\u7f6e\u9009\u9879\u548c\u5360\u4f4d\u7b26\u6587\u672c\u5c45\u4e2d\u663e\u793a */\n"
"}\n"
"\n"
"QComboBox::placeholder {\n"
"    color: gray; /* \u8bbe\u7f6e\u5360\u4f4d\u7b26\u6587\u672c\u7684\u989c\u8272 */\n"
"    font-size: 14px; /* \u8bbe\u7f6e\u5360\u4f4d\u7b26\u6587\u672c\u7684\u5b57\u4f53\u5927\u5c0f */\n"
"    font-family: Arial; /* \u8bbe\u7f6e\u5360\u4f4d\u7b26\u6587\u672c\u7684\u5b57\u4f53 */\n"
"    text-align: center; /* \u8bbe\u7f6e\u5360\u4f4d\u7b26\u6587\u672c\u5c45\u4e2d\u663e\u793a */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    text-align: center; /* \u8bbe\u7f6e\u4e0b\u62c9\u5217\u8868\u4e2d\u7684\u9879\u5c45\u4e2d\u663e\u793a */\n"
"}")
        self.comboBox_select_model.setMaxVisibleItems(13)
        self.line = QFrame(self.main_page)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(660, 100, 20, 400))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.layoutWidget = QWidget(self.main_page)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(0, 220, 151, 69))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.layoutWidget)
        self.label.setObjectName(u"label")
        font4 = QFont()
        font4.setPointSize(10)
        self.label.setFont(font4)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.label)

        self.horizontalSlider = QSlider(self.layoutWidget)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setOrientation(Qt.Orientation.Horizontal)
        self.horizontalSlider.setTickInterval(0)

        self.verticalLayout.addWidget(self.horizontalSlider)

        self.label_2 = QLabel(self.layoutWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.label_2)

        self.layoutWidget_2 = QWidget(self.main_page)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(0, 110, 151, 69))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.layoutWidget_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font4)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_3)

        self.horizontalSlider_IOC = QSlider(self.layoutWidget_2)
        self.horizontalSlider_IOC.setObjectName(u"horizontalSlider_IOC")
        self.horizontalSlider_IOC.setOrientation(Qt.Orientation.Horizontal)
        self.horizontalSlider_IOC.setTickInterval(0)

        self.verticalLayout_2.addWidget(self.horizontalSlider_IOC)

        self.IOU_label = QLabel(self.layoutWidget_2)
        self.IOU_label.setObjectName(u"IOU_label")
        self.IOU_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_2.addWidget(self.IOU_label)

        self.stop_Continue = QPushButton(self.main_page)
        self.stop_Continue.setObjectName(u"stop_Continue")
        self.stop_Continue.setGeometry(QRect(0, 420, 150, 36))
        self.stop_Continue.setFont(font1)
        self.Continue_test = QPushButton(self.main_page)
        self.Continue_test.setObjectName(u"Continue_test")
        self.Continue_test.setGeometry(QRect(0, 350, 150, 36))
        self.Continue_test.setFont(font1)
        self.stackedWidget.addWidget(self.main_page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1200, 33))
        self.menu = QMenu(self.menuBar)
        self.menu.setObjectName(u"menu")
        self.menu.setGeometry(QRect(273, 156, 121, 121))
        self.menu_3 = QMenu(self.menuBar)
        self.menu_3.setObjectName(u"menu_3")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menu.addAction(self.image_detection)
        self.menu.addAction(self.video_detection)
        self.menu.addAction(self.cammer_detection)
        self.menu_3.addAction(self.actionhug)
        self.menu_3.addAction(self.actionfaf)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u5371\u9669\u7269\u54c1\u68c0\u6d4b\u7cfb\u7edf", None))
        self.image_detection.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u7247\u68c0\u6d4b", None))
        self.video_detection.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u9891\u68c0\u6d4b", None))
        self.cammer_detection.setText(QCoreApplication.translate("MainWindow", u"\u6444\u50cf\u5934\u68c0\u6d4b", None))
        self.yolov10_action.setText(QCoreApplication.translate("MainWindow", u"yolov10n", None))
        self.actionyolov10n.setText(QCoreApplication.translate("MainWindow", u"yolov10n_", None))
        self.actionyolov10n_2.setText(QCoreApplication.translate("MainWindow", u"yolov10n_2", None))
        self.actionyolov10s.setText(QCoreApplication.translate("MainWindow", u"yolov10s", None))
        self.actionhug.setText(QCoreApplication.translate("MainWindow", u"\u8fc7\u5f80\u56fe\u7247\u68c0\u6d4b", None))
        self.actionfaf.setText(QCoreApplication.translate("MainWindow", u"\u8fc7\u5f80\u89c6\u9891\u68c0\u6d4b", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"\u81ea\u52a8\u767b\u5f55", None))
        self.designer_putton.setText(QCoreApplication.translate("MainWindow", u"\u6ce8\u518c\u8d26\u53f7", None))
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bf7\u8f93\u5165\u8d26\u53f7", None))
        self.lineEdit_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bf7\u8f93\u5165\u5bc6\u7801", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"\u8bb0\u4f4f\u5bc6\u7801", None))
        self.logic_main_putton.setText(QCoreApplication.translate("MainWindow", u"\u767b\u5f55", None))
        self.renewpassword_button.setText(QCoreApplication.translate("MainWindow", u"\u5fd8\u8bb0\u5bc6\u7801", None))
        self.register_putton.setText(QCoreApplication.translate("MainWindow", u"\u6ce8\u518c", None))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bf7\u8f93\u5165\u8d26\u53f7", None))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bf7\u8f93\u5165\u5bc6\u7801", None))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u518d\u6b21\u8f93\u5165\u5bc6\u7801\u8fdb\u884c\u786e\u8ba4", None))
        self.lineEdit_11.setText("")
        self.lineEdit_11.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e\u5bc6\u4fdd\u95ee\u9898", None))
        self.lineEdit_12.setText("")
        self.lineEdit_12.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e\u5bc6\u4fdd\u7b54\u6848", None))
        self.exit_logic_putton.setText(QCoreApplication.translate("MainWindow", u"\u53d6\u6d88", None))
        self.lineEdit_13.setText("")
        self.lineEdit_13.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bf7\u8f93\u5165\u8d26\u53f7", None))
        self.lineEdit_14.setText("")
        self.lineEdit_14.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bf7\u8f93\u5165\u5bc6\u7801", None))
        self.lineEdit_15.setText("")
        self.lineEdit_15.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u518d\u6b21\u8f93\u5165\u5bc6\u7801\u786e\u8ba4", None))
        self.lineEdit_17.setText("")
        self.lineEdit_17.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u56de\u7b54\u5bc6\u4fdd\u95ee\u9898", None))
        self.textEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u6b64\u5904\u663e\u793a\u5bc6\u4fdd\u95ee\u9898", None))
        self.select_protect_password_button.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2\u5bc6\u4fdd\u95ee\u9898", None))
        self.updata_password.setText(QCoreApplication.translate("MainWindow", u"\u4fee\u6539\u5bc6\u7801", None))
        self.exit_renew_logic_putton.setText(QCoreApplication.translate("MainWindow", u"\u53d6\u6d88", None))
        self.exit_main_putton.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa\u767b\u5f55", None))
        self.input.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u539f\u59cb\u5185\u5bb9", None))
        self.output.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u7ed3\u679c\u5185\u5bb9", None))
        self.comboBox_select_model.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u6a21\u578b\u9009\u62e9", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e\u6a21\u578b\u6700\u4f4e\u7f6e\u4fe1\u5ea6", None))
        self.label_2.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e\u6a21\u578b\u6700\u4f4e\u4ea4\u5e76\u6bd4", None))
        self.IOU_label.setText("")
        self.stop_Continue.setText(QCoreApplication.translate("MainWindow", u"\u505c\u6b62\u68c0\u6d4b", None))
        self.Continue_test.setText(QCoreApplication.translate("MainWindow", u"\u7ee7\u7eed\u68c0\u6d4b", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u9009\u62e9", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u"\u8fc7\u5f80\u68c0\u6d4b\u67e5\u8be2", None))
    # retranslateUi

